# -*- coding: utf-8 -*-
"""RAG-LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmtmQFiFYxeJy7eYxbbv6wC_wffYkGGy
"""

!pip install faiss-cpu

import os
import pickle
import faiss
import numpy as np
import torch
import xml.etree.ElementTree as ET
from sentence_transformers import SentenceTransformer
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    PegasusTokenizer,
    PegasusForConditionalGeneration
)

from google.colab import drive
drive.mount('/content/drive')

pip install transformers

# Path where the processed data will be stored
data_file = '/content/drive/MyDrive/dataset/processed_documents.pkl'

# Check if preprocessed file exists
if os.path.exists(data_file):
    # Load from file
    with open(data_file, 'rb') as f:
        documents = pickle.load(f)
    print(f"Loaded {len(documents)} Q-A pairs from cache.")
else:
    # Process the XML files and extract Q-A pairs
    dataset_path = '/content/drive/MyDrive/dataset/MedQuAD-master'
    documents = []

    for folder in os.listdir(dataset_path):
        folder_path = os.path.join(dataset_path, folder)
        if os.path.isdir(folder_path):
            for filename in os.listdir(folder_path):
                if filename.endswith('.xml'):
                    file_path = os.path.join(folder_path, filename)
                    try:
                        tree = ET.parse(file_path)
                        root = tree.getroot()

                        for qa_pair in root.findall('./QAPairs/QAPair'):
                            question = qa_pair.findtext('Question')
                            answer = qa_pair.findtext('Answer')

                            if question and answer:
                                doc_text = f"Q: {question.strip()}\nA: {answer.strip()}"
                                documents.append(doc_text)

                    except ET.ParseError:
                        print(f"Skipping corrupt XML: {file_path}")
                    except Exception as e:
                        print(f"Error processing {file_path}: {e}")

    # Save processed data for future runs
    with open(data_file, 'wb') as f:
        pickle.dump(documents, f)

    print(f"Extracted and saved {len(documents)} Q-A pairs.")

print(f"Total documents prepared: {len(documents)}")
print("\nSample document:")
print(documents[0])

# Path to save embeddings
embeddings_file = '/content/drive/MyDrive/dataset/document_embeddings.pkl'

if os.path.exists(embeddings_file):
    # Load saved embeddings
    with open(embeddings_file, 'rb') as f:
        document_embeddings = pickle.load(f)
    print(f"Loaded {len(document_embeddings)} document embeddings from cache.")
else:
    # Load the Sentence Transformer model
    model = SentenceTransformer('all-MiniLM-L6-v2')

    # Generate embeddings (this takes time)
    document_embeddings = model.encode(documents, show_progress_bar=True)

    # Save embeddings for future use
    with open(embeddings_file, 'wb') as f:
        pickle.dump(document_embeddings, f)

    print(f"Generated and saved {len(document_embeddings)} document embeddings.")

!pip install openai==0.28.0

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
model_name = "t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Load FAISS + Documents

faiss_index_file = '/content/drive/MyDrive/dataset/medquad_faiss.index'
documents_file = '/content/drive/MyDrive/dataset/processed_documents.pkl'
embeddings_file = '/content/drive/MyDrive/dataset/document_embeddings.pkl'

import pickle
import faiss
import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import os
import json

# File paths
faiss_index_file = '/content/drive/MyDrive/dataset/medquad_faiss.index'
documents_file = '/content/drive/MyDrive/dataset/processed_documents.pkl'
embeddings_file = '/content/drive/MyDrive/dataset/document_embeddings.pkl'

# Load stored documents
try:
    with open(documents_file, 'rb') as f:
        stored_documents = pickle.load(f)
    print("Loaded documents successfully.")
except Exception as e:
    print(f"Error loading documents: {e}")
    exit(1)

# Load embeddings
try:
    with open(embeddings_file, 'rb') as f:
        document_embeddings = pickle.load(f)
    print("Loaded embeddings successfully.")
except Exception as e:
    print(f"Error loading embeddings: {e}")
    exit(1)

# Load or build FAISS index
try:
    if os.path.exists(faiss_index_file):
        index = faiss.read_index(faiss_index_file)
        print("Loaded FAISS index from file.")
    else:
        dimension = document_embeddings.shape[1]
        index = faiss.IndexFlatL2(dimension)
        index.add(np.array(document_embeddings))
        faiss.write_index(index, faiss_index_file)
        print(f"Built and saved FAISS index with {index.ntotal} vectors.")
except Exception as e:
    print(f"Error with FAISS index: {e}")
    exit(1)

# Load T5-small Model
model_name = "t5-small"
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    print(f"Loaded T5 model on {device}.")
except Exception as e:
    print(f"Error loading T5 model: {e}")
    exit(1)

# Initialize SentenceTransformer
try:
    encoder = SentenceTransformer("all-MiniLM-L6-v2")
    print("Loaded SentenceTransformer model.")
except Exception as e:
    print(f"Error loading SentenceTransformer: {e}")
    exit(1)

# List of 50 medical questions
questions = [
    "What are common side effects of metformin?",
    "How is Type 2 diabetes mellitus diagnosed (what tests and thresholds)?",
    "What treatments are available for hypertension?",
    "What is the mechanism of action of statins (e.g. atorvastatin)?",
    "What are the indications for prescribing ACE inhibitors?",
    "What dietary modifications are recommended for patients with chronic kidney disease?",
    "What is the standard therapy for Parkinson’s disease?",
    "What is the difference between viral and bacterial meningitis in terms of diagnosis?",
    "What are risk factors for breast cancer?",
    "How is hypothyroidism diagnosed via lab tests?",
    "What are the adverse drug interactions with warfarin?",
    "What is the treatment protocol for acute asthma exacerbation?",
    "What precautions should patients take when using NSAIDs?",
    "What vaccines are recommended for older adults?",
    "What are the symptoms of heart failure?",
    "How is osteoporosis diagnosed and treated?",
    "What causes iron deficiency anemia, and how is it managed?",
    "What is the role of insulin therapy in type 1 diabetes?",
    "What are the clinical features of stroke and how should it be managed?",
    "What is the recommended management for gastroesophageal reflux disease (GERD)?",
    "How is hepatitis B transmitted, and what are preventive measures?",
    "What is the significance of HbA1c in diabetes monitoring?",
    "How is chronic obstructive pulmonary disease (COPD) diagnosed?",
    "What are the first-line medications for major depressive disorder?",
    "What are the contraindications for magnetic resonance imaging (MRI)?",
    "How is deep vein thrombosis (DVT) diagnosed and treated?",
    "What is stage 2 hypertension, and how should it be managed?",
    "What are the common side effects of chemotherapy?",
    "How is glaucoma detected and managed?",
    "What dietary advice is given to patients with hyperlipidemia?",
    "What is sepsis, and how is it treated?",
    "What are the symptoms and management of hypoglycemia?",
    "What are the risk factors and prevention strategies for osteoporosis?",
    "How is Crohn’s disease differentiated from ulcerative colitis?",
    "What is the management of acute myocardial infarction (heart attack)?",
    "What are the signs of menopause, and what hormone therapies are used?",
    "How is Alzheimer’s disease diagnosed and treated?",
    "What are the side effects and monitoring requirements for lithium therapy?",
    "How is hyperthyroidism (Graves’ disease) treated?",
    "What is anaphylaxis, and how is it managed emergently?",
    "How is pneumonia diagnosed and treated?",
    "What are the preventive measures for osteoporosis in postmenopausal women?",
    "What tests are used to screen for colon cancer?",
    "What are the pharmacologic options for type 2 diabetes when metformin alone is insufficient?",
    "How is chronic liver disease / cirrhosis managed?",
    "What lifestyle modifications help in managing hypertension?",
    "What are the warning signs of stroke (FAST criteria)?",
    "What are the management strategies for obesity?",
    "How is aortic aneurysm detected and what is the management approach?",
    "What are the recommended immunizations during pregnancy?"
]

# Dictionary to store questions, answers, and retrieved documents for debugging
results = []

# Process each question
for query in questions:
    print(f"\n{'='*50}\nProcessing Query: {query}\n{'='*50}")

    # Get embedding for query
    try:
        query_embedding = encoder.encode([query])
    except Exception as e:
        print(f"Error encoding query '{query}': {e}")
        results.append({"question": query, "answer": "Error encoding query", "retrieved_docs": []})
        continue

    # Retrieve top-k documents
    k = 3
    try:
        distances, indices = index.search(np.array(query_embedding), k)
        retrieved_docs = [stored_documents[i] for i in indices[0]]
        print("\nRetrieved Documents:")
        for i, doc in enumerate(retrieved_docs):
            print(f"Document {i+1}: {doc[:200]}...")  # Print first 200 chars for brevity
    except Exception as e:
        print(f"Error retrieving documents for '{query}': {e}")
        results.append({"question": query, "answer": "Error retrieving documents", "retrieved_docs": []})
        continue

    # Build prompt for T5
    prompt = "You are a helpful medical assistant. Answer the question clearly and concisely in 4–5 sentences. " \
             "Cover definition, causes, symptoms, and important details. Use ONLY the information from the provided documents. " \
             "If the document doesn’t have the answer, say 'Information not available'.\n\n"

    for i, doc in enumerate(retrieved_docs):
        prompt += f"Document {i+1}:\n{doc}\n\n"

    prompt += f"Question: {query}\nAnswer:"

    # Run inference
    try:
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)
        outputs = model.generate(
            **inputs,
            max_new_tokens=250,
            num_beams=6,
            length_penalty=1.2,
            repetition_penalty=1.5,
            no_repeat_ngram_size=3,
            early_stopping=True
        )
        answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        print(f"Error generating answer for '{query}': {e}")
        results.append({"question": query, "answer": "Error generating answer", "retrieved_docs": retrieved_docs})
        continue

    # Print answer
    print(f"\nAnswer:\n{answer}\n")

    # Store question, answer, and retrieved documents
    results.append({"question": query, "answer": answer, "retrieved_docs": retrieved_docs})

# Save results to a JSON file
output_file = "/content/drive/MyDrive/rag_test_results.json"
try:
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=4)
    print(f"\nResults saved to {output_file}")
except Exception as e:
    print(f"Error saving results to {output_file}: {e}")

from google.colab import drive
drive.mount('/content/drive')

#BART

import pickle
import faiss
import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import os
import json

# File paths
faiss_index_file = '/content/drive/MyDrive/dataset/medquad_faiss.index'
documents_file = '/content/drive/MyDrive/dataset/processed_documents.pkl'
embeddings_file = '/content/drive/MyDrive/dataset/document_embeddings.pkl'

# Load stored documents
try:
    with open(documents_file, 'rb') as f:
        stored_documents = pickle.load(f)
    print("Loaded documents successfully.")
except Exception as e:
    print(f"Error loading documents: {e}")
    exit(1)

# Load embeddings
try:
    with open(embeddings_file, 'rb') as f:
        document_embeddings = pickle.load(f)
    print("Loaded embeddings successfully.")
except Exception as e:
    print(f"Error loading embeddings: {e}")
    exit(1)

# Load or build FAISS index
try:
    if os.path.exists(faiss_index_file):
        index = faiss.read_index(faiss_index_file)
        print("Loaded FAISS index from file.")
    else:
        dimension = document_embeddings.shape[1]
        index = faiss.IndexFlatL2(dimension)
        index.add(np.array(document_embeddings))
        faiss.write_index(index, faiss_index_file)
        print(f"Built and saved FAISS index with {index.ntotal} vectors.")
except Exception as e:
    print(f"Error with FAISS index: {e}")
    exit(1)

# Load BART Model
model_name = "facebook/bart-large-cnn"
try:
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    print(f"Loaded BART model on {device}.")
except Exception as e:
    print(f"Error loading BART model: {e}")
    exit(1)

# Initialize SentenceTransformer
try:
    encoder = SentenceTransformer("all-MiniLM-L6-v2")
    print("Loaded SentenceTransformer model.")
except Exception as e:
    print(f"Error loading SentenceTransformer: {e}")
    exit(1)

# List of 50 medical questions
questions = [
    "What are common side effects of metformin?",
    "How is Type 2 diabetes mellitus diagnosed (what tests and thresholds)?",
    "What treatments are available for hypertension?",
    "What is the mechanism of action of statins (e.g. atorvastatin)?",
    "What are the indications for prescribing ACE inhibitors?",
    "What dietary modifications are recommended for patients with chronic kidney disease?",
    "What is the standard therapy for Parkinson’s disease?",
    "What is the difference between viral and bacterial meningitis in terms of diagnosis?",
    "What are risk factors for breast cancer?",
    "How is hypothyroidism diagnosed via lab tests?",
    "What are the adverse drug interactions with warfarin?",
    "What is the treatment protocol for acute asthma exacerbation?",
    "What precautions should patients take when using NSAIDs?",
    "What vaccines are recommended for older adults?",
    "What are the symptoms of heart failure?",
    "How is osteoporosis diagnosed and treated?",
    "What causes iron deficiency anemia, and how is it managed?",
    "What is the role of insulin therapy in type 1 diabetes?",
    "What are the clinical features of stroke and how should it be managed?",
    "What is the recommended management for gastroesophageal reflux disease (GERD)?",
    "How is hepatitis B transmitted, and what are preventive measures?",
    "What is the significance of HbA1c in diabetes monitoring?",
    "How is chronic obstructive pulmonary disease (COPD) diagnosed?",
    "What are the first-line medications for major depressive disorder?",
    "What are the contraindications for magnetic resonance imaging (MRI)?",
    "How is deep vein thrombosis (DVT) diagnosed and treated?",
    "What is stage 2 hypertension, and how should it be managed?",
    "What are the common side effects of chemotherapy?",
    "How is glaucoma detected and managed?",
    "What dietary advice is given to patients with hyperlipidemia?",
    "What is sepsis, and how is it treated?",
    "What are the symptoms and management of hypoglycemia?",
    "What are the risk factors and prevention strategies for osteoporosis?",
    "How is Crohn’s disease differentiated from ulcerative colitis?",
    "What is the management of acute myocardial infarction (heart attack)?",
    "What are the signs of menopause, and what hormone therapies are used?",
    "How is Alzheimer’s disease diagnosed and treated?",
    "What are the side effects and monitoring requirements for lithium therapy?",
    "How is hyperthyroidism (Graves’ disease) treated?",
    "What is anaphylaxis, and how is it managed emergently?",
    "How is pneumonia diagnosed and treated?",
    "What are the preventive measures for osteoporosis in postmenopausal women?",
    "What tests are used to screen for colon cancer?",
    "What are the pharmacologic options for type 2 diabetes when metformin alone is insufficient?",
    "How is chronic liver disease / cirrhosis managed?",
    "What lifestyle modifications help in managing hypertension?",
    "What are the warning signs of stroke (FAST criteria)?",
    "What are the management strategies for obesity?",
    "How is aortic aneurysm detected and what is the management approach?",
    "What are the recommended immunizations during pregnancy?"
]

# Dictionary to store questions, answers, and retrieved documents for debugging
results = []

# Process each question
for query in questions:
    print(f"\n{'='*50}\nProcessing Query: {query}\n{'='*50}")

    # Get embedding for query
    try:
        query_embedding = encoder.encode([query])
    except Exception as e:
        print(f"Error encoding query '{query}': {e}")
        results.append({"question": query, "answer": "Error encoding query", "retrieved_doc": ""})
        continue

    # Retrieve the most relevant document
    k = 1
    try:
        distances, indices = index.search(np.array(query_embedding), k)
        retrieved_doc = stored_documents[indices[0][0]]
        print(f"\nRetrieved Document:\n{retrieved_doc[:200]}...")  # Print first 200 chars for brevity
    except Exception as e:
        print(f"Error retrieving document for '{query}': {e}")
        results.append({"question": query, "answer": "Error retrieving document", "retrieved_doc": ""})
        continue

    # Build prompt for BART
    prompt = f"""
Document:
{retrieved_doc}

Instructions: You are a helpful medical assistant. Answer the question in 4-5 sentences covering:
- Definition
- Causes
- Symptoms
- Important details

Use ONLY information from the document. If the document doesn’t contain the answer, respond with 'Information not available'.
Question: {query}
"""

    # Run inference
    try:
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024).to(device)
        outputs = model.generate(
            **inputs,
            max_new_tokens=400,
            num_beams=6,
            length_penalty=2.0,
            repetition_penalty=2.5,
            no_repeat_ngram_size=3,
            early_stopping=True,
            do_sample=False
        )
        answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        print(f"Error generating answer for '{query}': {e}")
        results.append({"question": query, "answer": "Error generating answer", "retrieved_doc": retrieved_doc})
        continue

    # Print answer
    print(f"\nAnswer:\n{answer}\n")

    # Store question, answer, and retrieved document
    results.append({"question": query, "answer": answer, "retrieved_doc": retrieved_doc})

# Save results to a JSON file
output_file = "/content/drive/MyDrive/rag_bart_results.json"
try:
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=4)
    print(f"\nResults saved to {output_file}")
except Exception as e:
    print(f"Error saving results to {output_file}: {e}")

import pickle
import faiss
import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from transformers import PegasusTokenizer, PegasusForConditionalGeneration
import os
import json

# File paths
faiss_index_file = '/content/drive/MyDrive/dataset/medquad_faiss.index'
documents_file = '/content/drive/MyDrive/dataset/processed_documents.pkl'
embeddings_file = '/content/drive/MyDrive/dataset/document_embeddings.pkl'

# Load stored documents
try:
    with open(documents_file, 'rb') as f:
        stored_documents = pickle.load(f)
    print("Loaded documents successfully.")
except Exception as e:
    print(f"Error loading documents: {e}")
    exit(1)

# Load embeddings
try:
    with open(embeddings_file, 'rb') as f:
        document_embeddings = pickle.load(f)
    print("Loaded embeddings successfully.")
except Exception as e:
    print(f"Error loading embeddings: {e}")
    exit(1)

# Load or build FAISS index
try:
    if os.path.exists(faiss_index_file):
        index = faiss.read_index(faiss_index_file)
        print("Loaded FAISS index from file.")
    else:
        dimension = document_embeddings.shape[1]
        index = faiss.IndexFlatL2(dimension)
        index.add(np.array(document_embeddings))
        faiss.write_index(index, faiss_index_file)
        print(f"Built and saved FAISS index with {index.ntotal} vectors.")
except Exception as e:
    print(f"Error with FAISS index: {e}")
    exit(1)

# Load Pegasus Model
model_name = "google/pegasus-cnn_dailymail"
try:
    tokenizer = PegasusTokenizer.from_pretrained(model_name)
    model = PegasusForConditionalGeneration.from_pretrained(model_name)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    print(f"Loaded Pegasus model on {device}.")
except Exception as e:
    print(f"Error loading Pegasus model: {e}")
    exit(1)

# Initialize SentenceTransformer
try:
    encoder = SentenceTransformer("all-MiniLM-L6-v2")
    print("Loaded SentenceTransformer model.")
except Exception as e:
    print(f"Error loading SentenceTransformer: {e}")
    exit(1)

# List of 50 medical questions
questions = [
    "What are common side effects of metformin?",
    "How is Type 2 diabetes mellitus diagnosed (what tests and thresholds)?",
    "What treatments are available for hypertension?",
    "What is the mechanism of action of statins (e.g. atorvastatin)?",
    "What are the indications for prescribing ACE inhibitors?",
    "What dietary modifications are recommended for patients with chronic kidney disease?",
    "What is the standard therapy for Parkinson’s disease?",
    "What is the difference between viral and bacterial meningitis in terms of diagnosis?",
    "What are risk factors for breast cancer?",
    "How is hypothyroidism diagnosed via lab tests?",
    "What are the adverse drug interactions with warfarin?",
    "What is the treatment protocol for acute asthma exacerbation?",
    "What precautions should patients take when using NSAIDs?",
    "What vaccines are recommended for older adults?",
    "What are the symptoms of heart failure?",
    "How is osteoporosis diagnosed and treated?",
    "What causes iron deficiency anemia, and how is it managed?",
    "What is the role of insulin therapy in type 1 diabetes?",
    "What are the clinical features of stroke and how should it be managed?",
    "What is the recommended management for gastroesophageal reflux disease (GERD)?",
    "How is hepatitis B transmitted, and what are preventive measures?",
    "What is the significance of HbA1c in diabetes monitoring?",
    "How is chronic obstructive pulmonary disease (COPD) diagnosed?",
    "What are the first-line medications for major depressive disorder?",
    "What are the contraindications for magnetic resonance imaging (MRI)?",
    "How is deep vein thrombosis (DVT) diagnosed and treated?",
    "What is stage 2 hypertension, and how should it be managed?",
    "What are the common side effects of chemotherapy?",
    "How is glaucoma detected and managed?",
    "What dietary advice is given to patients with hyperlipidemia?",
    "What is sepsis, and how is it treated?",
    "What are the symptoms and management of hypoglycemia?",
    "What are the risk factors and prevention strategies for osteoporosis?",
    "How is Crohn’s disease differentiated from ulcerative colitis?",
    "What is the management of acute myocardial infarction (heart attack)?",
    "What are the signs of menopause, and what hormone therapies are used?",
    "How is Alzheimer’s disease diagnosed and treated?",
    "What are the side effects and monitoring requirements for lithium therapy?",
    "How is hyperthyroidism (Graves’ disease) treated?",
    "What is anaphylaxis, and how is it managed emergently?",
    "How is pneumonia diagnosed and treated?",
    "What are the preventive measures for osteoporosis in postmenopausal women?",
    "What tests are used to screen for colon cancer?",
    "What are the pharmacologic options for type 2 diabetes when metformin alone is insufficient?",
    "How is chronic liver disease / cirrhosis managed?",
    "What lifestyle modifications help in managing hypertension?",
    "What are the warning signs of stroke (FAST criteria)?",
    "What are the management strategies for obesity?",
    "How is aortic aneurysm detected and what is the management approach?",
    "What are the recommended immunizations during pregnancy?"
]

# Dictionary to store questions, answers, and retrieved documents for debugging
results = []

# Process each question
for query in questions:
    print(f"\n{'='*50}\nProcessing Query: {query}\n{'='*50}")

    # Get embedding for query
    try:
        query_embedding = encoder.encode([query])
    except Exception as e:
        print(f"Error encoding query '{query}': {e}")
        results.append({"question": query, "answer": "Error encoding query", "retrieved_doc": ""})
        continue

    # Retrieve the most relevant document
    k = 1
    try:
        distances, indices = index.search(np.array(query_embedding), k)
        retrieved_doc = stored_documents[indices[0][0]]
        print(f"\nRetrieved Document:\n{retrieved_doc[:200]}...")  # Print first 200 chars for brevity
    except Exception as e:
        print(f"Error retrieving document for '{query}': {e}")
        results.append({"question": query, "answer": "Error retrieving document", "retrieved_doc": ""})
        continue

    # Build prompt for Pegasus
    prompt = f"""
Document:
{retrieved_doc}

Instructions: You are a helpful medical assistant. Answer the following question in 4-5 sentences covering:
- Definition
- Causes
- Symptoms
- Important details

Use ONLY the information from the document. If the document doesn’t contain the answer, respond with 'Information not available'.
Question: {query}
Answer:
"""

    # Run inference
    try:
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024).to(device)
        outputs = model.generate(
            **inputs,
            max_length=200,
            num_beams=6,
            length_penalty=2.0,
            repetition_penalty=2.5,
            no_repeat_ngram_size=3,
            early_stopping=True,
            do_sample=False
        )
        answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    except Exception as e:
        print(f"Error generating answer for '{query}': {e}")
        results.append({"question": query, "answer": "Error generating answer", "retrieved_doc": retrieved_doc})
        continue

    # Print answer
    print(f"\nAnswer:\n{answer}\n")

    # Store question, answer, and retrieved document
    results.append({"question": query, "answer": answer, "retrieved_doc": retrieved_doc})

# Save results to a JSON file
output_file = "/content/drive/MyDrive/rag_pegasus_test_results.json"
try:
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=4)
    print(f"\nResults saved to {output_file}")
except Exception as e:
    print(f"Error saving results to {output_file}: {e}")

!pip install fuzzywuzzy

import json

# Define the 50 questions
questions = [
    "What are common side effects of metformin?",
    "How is Type 2 diabetes mellitus diagnosed (what tests and thresholds)?",
    "What treatments are available for hypertension?",
    "What is the mechanism of action of statins (e.g. atorvastatin)?",
    "What are the indications for prescribing ACE inhibitors?",
    "What dietary modifications are recommended for patients with chronic kidney disease?",
    "What is the standard therapy for Parkinson’s disease?",
    "What is the difference between viral and bacterial meningitis in terms of diagnosis?",
    "What are risk factors for breast cancer?",
    "How is hypothyroidism diagnosed via lab tests?",
    "What are the adverse drug interactions with warfarin?",
    "What is the treatment protocol for acute asthma exacerbation?",
    "What precautions should patients take when using NSAIDs?",
    "What vaccines are recommended for older adults?",
    "What are the symptoms of heart failure?",
    "How is osteoporosis diagnosed and treated?",
    "What causes iron deficiency anemia, and how is it managed?",
    "What is the role of insulin therapy in type 1 diabetes?",
    "What are the clinical features of stroke and how should it be managed?",
    "What is the recommended management for gastroesophageal reflux disease (GERD)?",
    "How is hepatitis B transmitted, and what are preventive measures?",
    "What is the significance of HbA1c in diabetes monitoring?",
    "How is chronic obstructive pulmonary disease (COPD) diagnosed?",
    "What are the first-line medications for major depressive disorder?",
    "What are the contraindications for magnetic resonance imaging (MRI)?",
    "How is deep vein thrombosis (DVT) diagnosed and treated?",
    "What is stage 2 hypertension, and how should it be managed?",
    "What are the common side effects of chemotherapy?",
    "How is glaucoma detected and managed?",
    "What dietary advice is given to patients with hyperlipidemia?",
    "What is sepsis, and how is it treated?",
    "What are the symptoms and management of hypoglycemia?",
    "What are the risk factors and prevention strategies for osteoporosis?",
    "How is Crohn’s disease differentiated from ulcerative colitis?",
    "What is the management of acute myocardial infarction (heart attack)?",
    "What are the signs of menopause, and what hormone therapies are used?",
    "How is Alzheimer’s disease diagnosed and treated?",
    "What are the side effects and monitoring requirements for lithium therapy?",
    "How is hyperthyroidism (Graves’ disease) treated?",
    "What is anaphylaxis, and how is it managed emergently?",
    "How is pneumonia diagnosed and treated?",
    "What are the preventive measures for osteoporosis in postmenopausal women?",
    "What tests are used to screen for colon cancer?",
    "What are the pharmacologic options for type 2 diabetes when metformin alone is insufficient?",
    "How is chronic liver disease / cirrhosis managed?",
    "What lifestyle modifications help in managing hypertension?",
    "What are the warning signs of stroke (FAST criteria)?",
    "What are the management strategies for obesity?",
    "How is aortic aneurysm detected and what is the management approach?",
    "What are the recommended immunizations during pregnancy?"
]

# Define ground truth answers
ground_truth = [
    {
        "question": "What are common side effects of metformin?",
        "answer": "Metformin, used to treat type 2 diabetes, commonly causes gastrointestinal side effects such as nausea, vomiting, diarrhea, and abdominal pain. A metallic taste in the mouth is also frequently reported. Long-term use may lead to vitamin B12 deficiency, which can cause fatigue or neuropathy. Lactic acidosis is a rare but serious side effect that requires immediate medical attention. These side effects often improve with dose adjustments or taking the medication with food."
    },
    {
        "question": "How is Type 2 diabetes mellitus diagnosed (what tests and thresholds)?",
        "answer": "Type 2 diabetes is diagnosed using blood tests like the A1C test (≥6.5%), fasting plasma glucose (FPG, ≥126 mg/dL), or oral glucose tolerance test (OGTT, 2-hour glucose ≥200 mg/dL). A random plasma glucose test (≥200 mg/dL) with symptoms like increased thirst or urination can also confirm diagnosis. Tests must be repeated on a separate day for confirmation unless clear symptoms are present. Prediabetes is indicated by A1C 5.7–6.4%, FPG 100–125 mg/dL, or OGTT 140–199 mg/dL. The A1C test reflects average blood glucose over 2–3 months and doesn’t require fasting."
    },
    {
        "question": "What treatments are available for hypertension?",
        "answer": "Hypertension is managed with medications such as diuretics, ACE inhibitors, ARBs, beta blockers, calcium channel blockers, and vasodilators. Diuretics reduce fluid volume, while ACE inhibitors and ARBs relax blood vessels by targeting the renin-angiotensin system. Lifestyle changes, including a low-sodium diet, regular exercise, weight loss, and stress management, are critical for blood pressure control. Often, multiple medications are combined to achieve a target blood pressure below 140/90 mmHg. Regular monitoring and adherence to treatment are essential to prevent complications like heart disease or stroke."
    },
    {
        "question": "What is the mechanism of action of statins (e.g. atorvastatin)?",
        "answer": "Statins, such as atorvastatin, work by inhibiting HMG-CoA reductase, an enzyme in the liver that produces cholesterol. This reduces low-density lipoprotein (LDL) cholesterol levels in the blood, lowering the risk of cardiovascular disease. Statins also increase LDL receptor activity, enhancing cholesterol clearance from the bloodstream. Additionally, they have anti-inflammatory effects and can stabilize arterial plaques, reducing the risk of heart attacks. They are typically prescribed for hyperlipidemia and cardiovascular risk reduction."
    },
    {
        "question": "What are the indications for prescribing ACE inhibitors?",
        "answer": "ACE inhibitors are prescribed for hypertension, heart failure, and chronic kidney disease, particularly in patients with diabetes or proteinuria. They are also used post-myocardial infarction to improve heart function and reduce mortality. These drugs block the conversion of angiotensin I to angiotensin II, reducing blood pressure and cardiac workload. They are beneficial in patients with left ventricular dysfunction or high cardiovascular risk. ACE inhibitors are often combined with other medications like diuretics for enhanced effect."
    },
    {
        "question": "What dietary modifications are recommended for patients with chronic kidney disease?",
        "answer": "Patients with chronic kidney disease (CKD) should follow a diet low in sodium, potassium, and phosphorus to reduce kidney strain. Protein intake is often moderated to limit waste buildup, though needs vary by CKD stage. Fluid intake may be restricted if fluid retention is an issue. A diet rich in fruits and vegetables low in potassium, such as apples or cabbage, is encouraged, and patients should avoid processed foods high in sodium. Consulting a dietitian is crucial to tailor the diet to individual kidney function and nutritional needs."
    },
    {
        "question": "What is the standard therapy for Parkinson’s disease?",
        "answer": "Parkinson’s disease is primarily treated with levodopa, often combined with carbidopa, to replenish dopamine levels and alleviate motor symptoms like tremors and rigidity. Dopamine agonists, MAO-B inhibitors, and anticholinergics are also used to manage symptoms, particularly in early stages. Physical therapy and exercise improve mobility and balance, complementing pharmacological treatment. Deep brain stimulation may be considered for advanced cases resistant to medication. Treatment is individualized, as symptoms and progression vary widely among patients."
    },
    {
        "question": "What is the difference between viral and bacterial meningitis in terms of diagnosis?",
        "answer": "Viral meningitis is typically diagnosed through cerebrospinal fluid (CSF) analysis showing lymphocytic predominance, normal or slightly elevated protein, and normal glucose levels. Bacterial meningitis, a medical emergency, shows neutrophilic predominance, high protein, and low glucose in CSF, often with positive bacterial cultures or PCR tests. Clinical symptoms like fever, headache, and neck stiffness are similar, but bacterial meningitis may present with more severe symptoms, such as altered mental status. Rapid diagnosis using lumbar puncture and imaging (e.g., CT scan) is critical for bacterial cases to initiate antibiotics promptly. Blood tests and Gram staining further aid in distinguishing the two."
    },
    {
        "question": "What are risk factors for breast cancer?",
        "answer": "Risk factors for breast cancer include being female, increasing age, and a family history of breast or ovarian cancer, particularly with BRCA1 or BRCA2 gene mutations. Lifestyle factors like obesity, alcohol consumption, and lack of physical activity increase risk, as does hormone replacement therapy or early menarche/late menopause. Dense breast tissue and prior radiation exposure to the chest are additional risk factors. Genetic predispositions account for 5–10% of cases, while most are linked to sporadic mutations. Regular screening and risk-reducing strategies, like weight management, can help mitigate risk."
    },
    {
        "question": "How is hypothyroidism diagnosed via lab tests?",
        "answer": "Hypothyroidism is diagnosed primarily through blood tests measuring thyroid-stimulating hormone (TSH) and free thyroxine (T4) levels. Elevated TSH with low free T4 confirms primary hypothyroidism, often caused by autoimmune thyroiditis (Hashimoto’s). If TSH is elevated but T4 is normal, subclinical hypothyroidism may be present. Additional tests, like anti-thyroid peroxidase antibodies, can identify autoimmune causes. Regular monitoring of TSH levels is needed to adjust treatment, typically with levothyroxine."
    },
    {
        "question": "What are the adverse drug interactions with warfarin?",
        "answer": "Warfarin, an anticoagulant, interacts with many drugs, increasing or decreasing its blood-thinning effect, which can lead to bleeding or clotting risks. Drugs like NSAIDs, aspirin, and antibiotics (e.g., erythromycin) increase bleeding risk by enhancing warfarin’s effect or inhibiting its metabolism. Medications like rifampin or carbamazepine reduce warfarin’s efficacy by inducing its metabolism. Foods high in vitamin K (e.g., leafy greens) can counteract warfarin’s effect. Regular INR monitoring is essential to manage these interactions and adjust doses."
    },
    {
        "question": "What is the treatment protocol for acute asthma exacerbation?",
        "answer": "Acute asthma exacerbations are treated with short-acting beta-agonists (e.g., albuterol) via nebulizer or inhaler to relieve bronchospasm. Systemic corticosteroids, such as oral prednisone or IV methylprednisolone, reduce airway inflammation. Oxygen therapy is used to maintain adequate oxygen saturation, especially if hypoxia is present. In severe cases, anticholinergics (e.g., ipratropium) or magnesium sulfate may be added. Patients are monitored closely, and hospitalization may be required for persistent symptoms."
    },
    {
        "question": "What precautions should patients take when using NSAIDs?",
        "answer": "Nonsteroidal anti-inflammatory drugs (NSAIDs) like ibuprofen can cause gastrointestinal bleeding, so they should be taken with food or a proton pump inhibitor. Patients with kidney disease, heart failure, or hypertension should use NSAIDs cautiously due to risks of kidney damage or fluid retention. Long-term use increases cardiovascular risks, particularly in those with existing heart conditions. NSAIDs should be avoided in patients with peptic ulcers or those taking anticoagulants like warfarin. Always consult a healthcare provider for personalized dosing and monitoring."
    },
    {
        "question": "What vaccines are recommended for older adults?",
        "answer": "Older adults (age 65 and above) are recommended to receive the annual influenza vaccine and the pneumococcal vaccines (PCV13 and PPSV23) to protect against pneumonia. The shingles vaccine (Zoster Vaccine Recombinant, Adjuvanted) is advised to prevent herpes zoster and its complications. The Tdap vaccine, protecting against tetanus, diphtheria, and pertussis, should be updated every 10 years. COVID-19 vaccination, including boosters, is critical for this age group. Vaccination schedules may vary based on health conditions, so consulting a healthcare provider is essential."
    },
    {
        "question": "What are the symptoms of heart failure?",
        "answer": "Heart failure causes symptoms like shortness of breath, especially during activity or when lying down, and persistent fatigue. Swelling in the legs, ankles, or feet (edema) is common due to fluid retention. Patients may experience rapid or irregular heartbeats and reduced exercise tolerance. Other symptoms include persistent cough, weight gain from fluid buildup, and difficulty concentrating. Symptoms vary by severity, and early medical intervention is crucial to manage progression."
    },
    {
        "question": "How is osteoporosis diagnosed and treated?",
        "answer": "Osteoporosis is diagnosed using a bone density test, typically a DEXA scan, which measures bone mineral density and assigns a T-score (≤-2.5 indicates osteoporosis). Treatment includes bisphosphonates (e.g., alendronate) to slow bone loss and increase bone strength. Calcium and vitamin D supplements support bone health, while weight-bearing exercises improve bone density and balance. Lifestyle changes, like quitting smoking and reducing alcohol, are recommended. In severe cases, medications like denosumab or teriparatide may be prescribed."
    },
    {
        "question": "What causes iron deficiency anemia, and how is it managed?",
        "answer": "Iron deficiency anemia is caused by low iron levels due to blood loss (e.g., heavy menstruation, gastrointestinal bleeding), poor dietary intake, or malabsorption (e.g., celiac disease). Symptoms include fatigue, pale skin, and shortness of breath. Management involves oral iron supplements (e.g., ferrous sulfate) to restore iron levels, taken with vitamin C to enhance absorption. Treating underlying causes, like ulcers or dietary deficiencies, is essential. In severe cases, intravenous iron or blood transfusions may be needed."
    },
    {
        "question": "What is the role of insulin therapy in type 1 diabetes?",
        "answer": "In type 1 diabetes, insulin therapy is essential because the pancreas produces little to no insulin due to autoimmune destruction of beta cells. It regulates blood glucose levels by facilitating glucose uptake into cells and inhibiting liver glucose production. Patients typically use a combination of long-acting (basal) and short-acting (bolus) insulin to mimic natural insulin release. Insulin is delivered via injections or an insulin pump, with doses adjusted based on blood glucose monitoring. Continuous glucose monitoring and education on carbohydrate counting improve glycemic control."
    },
    {
        "question": "What are the clinical features of stroke and how should it be managed?",
        "answer": "Stroke presents with sudden symptoms like facial drooping, arm weakness, speech difficulty, and time urgency (FAST criteria). Other features include vision loss, confusion, and difficulty walking. Ischemic strokes, caused by blood clots, are treated with thrombolytics (e.g., tPA) within 4.5 hours or mechanical thrombectomy for large clots. Hemorrhagic strokes require blood pressure control and sometimes surgery to stop bleeding. Immediate medical attention and rehabilitation (e.g., physical therapy) are critical for recovery."
    },
    {
        "question": "What is the recommended management for gastroesophageal reflux disease (GERD)?",
        "answer": "GERD, characterized by acid reflux causing heartburn, is managed with lifestyle changes like avoiding trigger foods (e.g., spicy or fatty foods), eating smaller meals, and elevating the head during sleep. Proton pump inhibitors (PPIs) or H2 blockers reduce acid production, providing symptom relief. Weight loss and avoiding lying down after meals can prevent reflux episodes. In severe cases, surgical options like fundoplication may be considered. Regular monitoring is needed to prevent complications like esophageal strictures."
    },
    {
        "question": "How is hepatitis B transmitted, and what are preventive measures?",
        "answer": "Hepatitis B is transmitted through blood, semen, or other bodily fluids, commonly via unprotected sex, sharing needles, or from mother to child during childbirth. Healthcare workers may be exposed through needlestick injuries. Preventive measures include the hepatitis B vaccine, which is highly effective and recommended for all infants and high-risk adults. Safe practices, like using condoms and avoiding shared needles, reduce transmission risk. Screening pregnant women and treating newborns with antivirals can prevent perinatal transmission."
    },
    {
        "question": "What is the significance of HbA1c in diabetes monitoring?",
        "answer": "HbA1c measures average blood glucose levels over 2–3 months, reflecting long-term diabetes control. A level below 7% is the target for most diabetic patients to reduce complications like neuropathy or retinopathy. Elevated HbA1c indicates poor glucose control, prompting treatment adjustments. It’s tested every 3–6 months and doesn’t require fasting, unlike daily glucose checks. Certain conditions, like anemia, may affect HbA1c accuracy, requiring alternative monitoring."
    },
    {
        "question": "How is chronic obstructive pulmonary disease (COPD) diagnosed?",
        "answer": "COPD is diagnosed using spirometry, which measures lung function by assessing forced expiratory volume (FEV1) and forced vital capacity (FVC), with an FEV1/FVC ratio <0.7 indicating obstruction. Symptoms like chronic cough, sputum production, and shortness of breath support the diagnosis. Chest X-rays or CT scans rule out other conditions and assess lung damage. Arterial blood gas tests may evaluate oxygen and carbon dioxide levels in severe cases. Smoking history and environmental exposures are key risk factors considered during diagnosis."
    },
    {
        "question": "What are the first-line medications for major depressive disorder?",
        "answer": "Selective serotonin reuptake inhibitors (SSRIs), such as sertraline and fluoxetine, are first-line medications for major depressive disorder due to their efficacy and safety profile. Serotonin-norepinephrine reuptake inhibitors (SNRIs), like venlafaxine, are also commonly used. These drugs increase neurotransmitter levels to improve mood and reduce symptoms like sadness and loss of interest. Treatment is tailored to the patient, with therapy (e.g., CBT) often combined with medication. Side effects, like nausea or insomnia, are monitored, and adjustments may be needed."
    },
    {
        "question": "What are the contraindications for magnetic resonance imaging (MRI)?",
        "answer": "MRI is contraindicated in patients with certain metallic implants, such as pacemakers, cochlear implants, or older aneurysm clips, due to magnetic field risks. Patients with severe claustrophobia may be unable to tolerate the procedure without sedation. Kidney disease can limit the use of gadolinium contrast due to the risk of nephrogenic systemic fibrosis. Foreign metal objects (e.g., shrapnel) or tattoos with metallic ink may pose risks. A thorough screening questionnaire ensures safety before the procedure."
    },
    {
        "question": "How is deep vein thrombosis (DVT) diagnosed and treated?",
        "answer": "DVT is diagnosed using ultrasound to detect blood clots in deep veins, typically in the legs. D-dimer blood tests can support diagnosis, with elevated levels suggesting clot presence, though further imaging is needed. Treatment involves anticoagulants (e.g., heparin, warfarin, or direct oral anticoagulants) to prevent clot growth and reduce recurrence risk. Compression stockings help reduce swelling and prevent complications like post-thrombotic syndrome. In severe cases, thrombolytic therapy or surgical intervention may be required."
    },
    {
        "question": "What is stage 2 hypertension, and how should it be managed?",
        "answer": "Stage 2 hypertension is defined as a systolic blood pressure ≥140 mmHg or diastolic ≥90 mmHg, based on multiple readings. It increases the risk of heart disease, stroke, and kidney damage. Management includes two or more medications, such as thiazide diuretics and ACE inhibitors, to lower blood pressure. Lifestyle changes, like reducing sodium intake, increasing physical activity, and quitting smoking, are critical. Regular blood pressure monitoring and follow-up are essential to achieve control below 140/90 mmHg."
    },
    {
        "question": "What are the common side effects of chemotherapy?",
        "answer": "Chemotherapy commonly causes side effects like nausea, vomiting, fatigue, and hair loss due to its impact on rapidly dividing cells. Bone marrow suppression can lead to anemia, increased infection risk, and easy bruising. Gastrointestinal issues, such as diarrhea or mouth sores, are frequent, as are neurological effects like peripheral neuropathy. Side effects vary by drug and patient, and supportive care (e.g., antiemetics) helps manage them. Regular monitoring ensures early detection of severe complications like organ toxicity."
    },
    {
        "question": "How is glaucoma detected and managed?",
        "answer": "Glaucoma is detected through eye exams measuring intraocular pressure (tonometry), assessing optic nerve damage (ophthalmoscopy), and testing visual fields. Gonioscopy evaluates the eye’s drainage angle, and imaging (e.g., OCT) monitors nerve damage. Management includes eye drops (e.g., prostaglandin analogs) to lower pressure, and oral medications in some cases. Laser therapy or surgery (e.g., trabeculectomy) may be needed if medications fail. Regular monitoring is crucial to prevent vision loss."
    },
    {
        "question": "What dietary advice is given to patients with hyperlipidemia?",
        "answer": "Patients with hyperlipidemia should follow a heart-healthy diet low in saturated fats, trans fats, and cholesterol, emphasizing fruits, vegetables, and whole grains. Foods rich in omega-3 fatty acids, like fatty fish, and soluble fiber, like oats, help lower LDL cholesterol. Limiting red meat and processed foods while choosing lean proteins and plant-based options is recommended. Moderate alcohol consumption and avoiding sugary beverages support lipid control. Consulting a dietitian ensures personalized dietary planning."
    },
    {
        "question": "What is sepsis, and how is it treated?",
        "answer": "Sepsis is a life-threatening condition caused by the body’s extreme response to infection, leading to organ dysfunction. Symptoms include fever, rapid heart rate, confusion, and low blood pressure. Treatment involves prompt administration of broad-spectrum antibiotics to target the underlying infection. Intravenous fluids and vasopressors stabilize blood pressure, and oxygen therapy supports organ function. Early recognition and intensive care are critical to improve survival rates."
    },
    {
        "question": "What are the symptoms and management of hypoglycemia?",
        "answer": "Hypoglycemia, or low blood sugar, causes symptoms like shakiness, sweating, confusion, and irritability, with severe cases leading to seizures or unconsciousness. It occurs in diabetic patients due to excess insulin, skipped meals, or intense exercise. Management involves consuming 15–20 grams of fast-acting carbohydrates (e.g., glucose tablets, juice) and rechecking blood sugar after 15 minutes. For severe cases, glucagon injections or IV glucose are used. Preventing recurrence requires adjusting medications and meal planning."
    },
    {
        "question": "What are the risk factors and prevention strategies for osteoporosis?",
        "answer": "Risk factors for osteoporosis include aging, female gender, low body weight, smoking, excessive alcohol, and family history of fractures. Postmenopausal women are at higher risk due to estrogen decline, as are those with low calcium or vitamin D intake. Prevention includes weight-bearing exercises, like walking, to strengthen bones, and adequate calcium (1,200 mg/day) and vitamin D (800 IU/day) intake. Quitting smoking and limiting alcohol reduce risk. Bone density screening helps identify those needing early intervention."
    },
    {
        "question": "How is Crohn’s disease differentiated from ulcerative colitis?",
        "answer": "Crohn’s disease and ulcerative colitis (UC) are inflammatory bowel diseases, but Crohn’s can affect any part of the gastrointestinal tract, often discontinuously, while UC is limited to the colon with continuous inflammation. Crohn’s causes transmural inflammation, leading to fistulas and strictures, whereas UC affects only the mucosal layer, causing bloody diarrhea. Diagnosis involves colonoscopy, showing skip lesions in Crohn’s and uniform inflammation in UC. Biopsies and imaging (e.g., CT) confirm the diagnosis. Symptoms like abdominal pain and diarrhea occur in both, but Crohn’s may include weight loss and perianal disease."
    },
    {
        "question": "What is the management of acute myocardial infarction (heart attack)?",
        "answer": "Acute myocardial infarction (MI) is managed with immediate interventions like aspirin to prevent further clotting and oxygen to improve cardiac oxygenation. Percutaneous coronary intervention (PCI) within 90 minutes is preferred to restore blood flow, or thrombolytics if PCI is unavailable. Medications like beta blockers, ACE inhibitors, and statins are started to reduce cardiac workload and prevent recurrence. Nitroglycerin relieves chest pain, and anticoagulants (e.g., heparin) are used. Post-MI, cardiac rehabilitation and lifestyle changes are critical for recovery."
    },
    {
        "question": "What are the signs of menopause, and what hormone therapies are used?",
        "answer": "Menopause, the cessation of menstruation, causes symptoms like hot flashes, night sweats, vaginal dryness, and mood changes due to declining estrogen levels. Irregular periods often precede menopause, and bone loss increases osteoporosis risk. Hormone replacement therapy (HRT), using estrogen or combined estrogen-progestin, relieves symptoms like hot flashes and prevents bone loss. HRT is tailored to the patient, with risks like breast cancer considered. Non-hormonal options, like SSRIs, may be used for symptom relief."
    },
    {
        "question": "How is Alzheimer’s disease diagnosed and treated?",
        "answer": "Alzheimer’s disease is diagnosed through cognitive testing, medical history, and ruling out other causes of dementia with imaging (e.g., MRI, PET scans). Memory loss, confusion, and difficulty with daily tasks are hallmark symptoms. Treatment includes cholinesterase inhibitors (e.g., donepezil) to boost acetylcholine levels and memantine for moderate-to-severe cases. Non-drug therapies, like cognitive stimulation and lifestyle changes, support symptom management. No cure exists, so treatment focuses on slowing progression and improving quality of life."
    },
    {
        "question": "What are the side effects and monitoring requirements for lithium therapy?",
        "answer": "Lithium, used for bipolar disorder, can cause side effects like nausea, tremor, weight gain, and increased thirst or urination. Long-term use may lead to hypothyroidism or kidney dysfunction. Regular blood tests monitor lithium levels (target 0.6–1.2 mmol/L) to prevent toxicity, which can cause confusion or seizures. Thyroid and kidney function tests are required every 6–12 months. Patients should maintain consistent sodium and fluid intake to avoid toxicity."
    },
    {
        "question": "How is hyperthyroidism (Graves’ disease) treated?",
        "answer": "Graves’ disease, a common cause of hyperthyroidism, is treated with antithyroid drugs like methimazole to reduce thyroid hormone production. Beta blockers (e.g., propranolol) manage symptoms like rapid heart rate and tremors. Radioactive iodine therapy may destroy overactive thyroid tissue, often leading to hypothyroidism requiring levothyroxine. In severe cases, thyroidectomy (surgical removal) is an option. Treatment choice depends on patient factors like age and pregnancy status."
    },
    {
        "question": "What is anaphylaxis, and how is it managed emergently?",
        "answer": "Anaphylaxis is a severe allergic reaction causing symptoms like difficulty breathing, swelling, hives, and low blood pressure, often triggered by foods, medications, or insect stings. Immediate management involves administering epinephrine (e.g., EpiPen) to reverse airway constriction and stabilize blood pressure. Antihistamines and corticosteroids treat secondary symptoms like itching and inflammation. Oxygen and IV fluids are given in severe cases, and patients require emergency medical attention. Patients with a history of anaphylaxis should carry epinephrine auto-injectors."
    },
    {
        "question": "How is pneumonia diagnosed and treated?",
        "answer": "Pneumonia is diagnosed using chest X-rays to detect lung infiltrates, along with symptoms like cough, fever, and shortness of breath. Sputum cultures, blood tests, or pulse oximetry help identify the cause (bacterial, viral) and severity. Bacterial pneumonia is treated with antibiotics (e.g., amoxicillin, azithromycin), while viral cases may require antivirals. Supportive care includes oxygen therapy and fluids for hydration. Severe cases may require hospitalization and respiratory support."
    },
    {
        "question": "What are the preventive measures for osteoporosis in postmenopausal women?",
        "answer": "Postmenopausal women can prevent osteoporosis by ensuring adequate calcium (1,200 mg/day) and vitamin D (800 IU/day) intake through diet or supplements. Weight-bearing exercises, like walking or strength training, improve bone density and reduce fracture risk. Quitting smoking and limiting alcohol consumption are crucial, as both weaken bones. Bone density screening (DEXA scan) identifies at-risk women for early intervention. Medications like bisphosphonates may be prescribed for those with low bone density."
    },
    {
        "question": "What tests are used to screen for colon cancer?",
        "answer": "Colon cancer screening includes colonoscopy, which examines the entire colon for polyps or cancer every 10 years starting at age 45. Fecal immunochemical tests (FIT) detect blood in stool annually and are non-invasive. Stool DNA tests (e.g., Cologuard) check for blood and genetic markers every 3 years. CT colonography (virtual colonoscopy) is an imaging alternative every 5 years. Positive non-invasive tests require follow-up with colonoscopy for confirmation."
    },
    {
        "question": "What are the pharmacologic options for type 2 diabetes when metformin alone is insufficient?",
        "answer": "When metformin is insufficient for type 2 diabetes, additional medications include sulfonylureas (e.g., glipizide) to stimulate insulin release, or DPP-4 inhibitors (e.g., sitagliptin) to enhance insulin secretion. SGLT2 inhibitors (e.g., empagliflozin) reduce glucose reabsorption in kidneys, and GLP-1 receptor agonists (e.g., liraglutide) promote insulin release and weight loss. Thiazolidinediones (e.g., pioglitazone) improve insulin sensitivity. Insulin therapy may be added for advanced cases. Treatment is tailored based on patient factors like weight and kidney function."
    },
    {
        "question": "How is chronic liver disease / cirrhosis managed?",
        "answer": "Chronic liver disease and cirrhosis are managed by addressing the underlying cause, such as stopping alcohol use or treating hepatitis. Medications like antivirals for hepatitis or diuretics for fluid retention (ascites) are used. Avoiding hepatotoxic drugs and maintaining a low-sodium diet prevent complications. Regular monitoring with imaging and liver function tests tracks progression. In advanced cases, liver transplantation may be necessary."
    },
    {
        "question": "What lifestyle modifications help in managing hypertension?",
        "answer": "Lifestyle modifications for hypertension include adopting a low-sodium diet, such as the DASH diet, rich in fruits, vegetables, and whole grains. Regular aerobic exercise (e.g., 150 minutes/week) lowers blood pressure, as does maintaining a healthy weight. Quitting smoking and limiting alcohol (≤1 drink/day for women, ≤2 for men) reduce cardiovascular risk. Stress management through techniques like meditation also helps. These changes can reduce blood pressure by 5–20 mmHg and enhance medication efficacy."
    },
    {
        "question": "What are the warning signs of stroke (FAST criteria)?",
        "answer": "The FAST criteria identify stroke warning signs: Face drooping (one side of the face sags), Arm weakness (one arm drifts downward when raised), Speech difficulty (slurred or incomprehensible speech), and Time to call emergency services. Other signs include sudden vision loss, confusion, or severe headache. These symptoms typically occur suddenly and require immediate medical attention. Early recognition improves outcomes by enabling rapid treatment like thrombolytics. Public education on FAST is critical for timely intervention."
    },
    {
        "question": "What are the management strategies for obesity?",
        "answer": "Obesity is managed through lifestyle changes, including a calorie-controlled diet rich in whole foods and low in processed sugars. Regular physical activity (150–300 minutes/week of moderate exercise) promotes weight loss and health. Behavioral therapy helps address eating habits and emotional triggers. Medications like orlistat or GLP-1 agonists (e.g., semaglutide) may be prescribed for significant obesity. Bariatric surgery, such as gastric bypass, is considered for severe cases with comorbidities."
    },
    {
        "question": "How is aortic aneurysm detected and what is the management approach?",
        "answer": "Aortic aneurysms are detected through imaging like ultrasound, CT, or MRI, often incidentally during exams for other conditions. Screening is recommended for high-risk groups, like older men with a smoking history. Small aneurysms (<5.5 cm) are monitored with regular imaging and blood pressure control to slow growth. Large or symptomatic aneurysms may require surgical repair, such as endovascular stenting or open surgery. Lifestyle changes, like quitting smoking, reduce rupture risk."
    },
    {
        "question": "What are the recommended immunizations during pregnancy?",
        "answer": "Pregnant women are recommended to receive the Tdap vaccine (tetanus, diphtheria, pertussis) between 27–36 weeks to protect against whooping cough in newborns. The influenza vaccine is safe and advised during flu season to prevent severe illness. COVID-19 vaccination is recommended to reduce risks to mother and baby. Hepatitis B vaccine may be given if the mother is at risk. Live vaccines, like MMR or varicella, are contraindicated during pregnancy."
    }
]

# Save ground truth to JSON
output_file = '/content/drive/MyDrive/dataset/ground_truth.json'
try:
    with open(output_file, 'w') as f:
        json.dump(ground_truth, f, indent=4)
    print(f"Ground truth saved to {output_file}")
except Exception as e:
    print(f"Error saving ground truth: {e}")

!pip install rouge-score nltk transformers sentence-transformers bert-score numpy

# --------------------------------------------------------------
#  RAG evaluation – supports both "retrieved_docs" and "retrieved_doc"
# --------------------------------------------------------------
import json
import numpy as np
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from transformers import pipeline
from bert_score import score as bert_score
import torch
from scipy.stats import ttest_rel

# --------------------------  FILE PATHS  --------------------------
t5_results_file      = '/content/drive/MyDrive/rag_test_results.json'
bart_results_file    = '/content/drive/MyDrive/rag_bart_results.json'
pegasus_results_file = '/content/drive/MyDrive/rag_pegasus_test_results.json'
ground_truth_file    = '/content/drive/MyDrive/dataset/ground_truth.json'

# --------------------------  LOAD DATA  --------------------------
try:
    with open(ground_truth_file, 'r') as f:      ground_truth = json.load(f)
    with open(t5_results_file, 'r') as f:        t5_results = json.load(f)
    with open(bart_results_file, 'r') as f:      bart_results = json.load(f)
    with open(pegasus_results_file, 'r') as f:   pegasus_results = json.load(f)
    print("All files loaded.")
except Exception as e:
    print(f"Error loading files: {e}")
    raise

if not (len(t5_results) == len(bart_results) == len(pegasus_results) == len(ground_truth)):
    print("Question count mismatch!")
    raise ValueError("All result files must contain the same number of questions.")

# --------------------------  HELPERS  --------------------------
def clean_answer(answer):
    """Strip prefixes that sometimes appear in the raw generation."""
    if not answer or isinstance(answer, dict):
        return ""
    for prefix in ["Document", "Q:", "A:"]:
        if answer.startswith(prefix):
            answer = answer[answer.find(":") + 1:].strip()
    return answer.strip()

def get_context(entry):
    """
    Return a single string that can be used as the NLI premise.
    * list  -> ' '.join(...)
    * string -> return as-is
    * missing -> return empty string (faithfulness = 0)
    """
    if 'retrieved_docs' in entry and entry['retrieved_docs']:
        return ' '.join(entry['retrieved_docs'])
    if 'retrieved_doc' in entry and entry['retrieved_doc']:
        return entry['retrieved_doc']
    return ""

# --------------------------  EVALUATION  --------------------------
def evaluate_model(results, ground_truth):
    rouge_scorer_obj = rouge_scorer.RougeScorer(['rouge1','rouge2','rougeL'], use_stemmer=True)
    nli = pipeline("text-classification",
                   model="roberta-large-mnli",
                   device=0 if torch.cuda.is_available() else -1)

    r1, r2, rL, bleu, bert_f1, faith = [], [], [], [], [], []

    for res, gt in zip(results, ground_truth):
        if res['question'] != gt['question']:
            print(f"Warning: question mismatch – {res['question']}")
            continue

        gen = clean_answer(res['answer'])
        ref = gt['answer']
        ctx = get_context(res)

        if not gen or "Error" in gen:
            print(f"Skipping empty/invalid answer for: {res['question']}")
            continue

        # ---- ROUGE ----
        scores = rouge_scorer_obj.score(ref, gen)
        r1.append(scores['rouge1'].fmeasure)
        r2.append(scores['rouge2'].fmeasure)
        rL.append(scores['rougeL'].fmeasure)

        # ---- BLEU ----
        bleu.append(sentence_bleu([ref.split()], gen.split(),
                                 smoothing_function=SmoothingFunction().method1))

        # ---- FAITHFULNESS (NLI) ----
        faith_score = 0
        if ctx:
            try:
                inp = f"{ctx} </s></s> {gen}"
                out = nli(inp, truncation=True, max_length=512)[0]
                faith_score = 1 if out['label'] == 'ENTAILMENT' else 0
            except Exception as e:
                print(f"NLI error ({res['question']}): {e}")
        else:
            print(f"No context for faithfulness – {res['question']}")
        faith.append(faith_score)

    # ---- BERTScore (batch) ----
    valid_gen = [clean_answer(r['answer']) for r in results
                 if r['answer'] and "Error" not in str(r['answer'])]
    valid_ref = [gt['answer'] for gt, r in zip(ground_truth, results)
                 if r['answer'] and "Error" not in str(r['answer'])]
    bert_f1_list = [0] * len(results)
    if valid_gen:
        _, _, f1 = bert_score(valid_gen, valid_ref, lang="en")
        bert_f1_list = f1.tolist()

    return {
        'ROUGE-1'      : np.mean(r1) if r1 else 0,
        'ROUGE-2'      : np.mean(r2) if r2 else 0,
        'ROUGE-L'      : np.mean(rL) if rL else 0,
        'BLEU'         : np.mean(bleu) if bleu else 0,
        'BERTScore F1' : np.mean(bert_f1_list) if bert_f1_list else 0,
        'Faithfulness' : np.mean(faith) if faith else 0
    }

# --------------------------  RUN  --------------------------
t5_scores      = evaluate_model(t5_results,      ground_truth)
bart_scores    = evaluate_model(bart_results,    ground_truth)
pegasus_scores = evaluate_model(pegasus_results, ground_truth)

# --------------------------  TABLE  --------------------------
print("\nModel Comparison Table:")
print("Model\tROUGE-1\tROUGE-2\tROUGE-L\tBLEU\tBERTScore F1\tFaithfulness")
for name, s in zip(["T5","BART","Pegasus"], [t5_scores, bart_scores, pegasus_scores]):
    print(f"{name}\t{s['ROUGE-1']:.4f}\t{s['ROUGE-2']:.4f}\t"
          f"{s['ROUGE-L']:.4f}\t{s['BLEU']:.4f}\t"
          f"{s['BERTScore F1']:.4f}\t{s['Faithfulness']:.4f}")

# --------------------------  PAIRED T-TEST  --------------------------
def compare_models(metric, res1, res2, name1, name2):
    # Build per-question scores (only valid answers)
    scores1, scores2 = [], []
    for r1, r2 in zip(res1, res2):
        a1 = clean_answer(r1['answer'])
        a2 = clean_answer(r2['answer'])
        if not a1 or not a2 or "Error" in a1 or "Error" in a2:
            continue
        # tiny temporary entry just to reuse evaluate_model
        tmp1 = [{'answer': a1, **r1}]
        tmp2 = [{'answer': a2, **r2}]
        scores1.append(evaluate_model(tmp1, ground_truth)[metric])
        scores2.append(evaluate_model(tmp2, ground_truth)[metric])
    if len(scores1) > 1:
        t, p = ttest_rel(scores1, scores2)
        print(f"\nPaired t-test {metric} ({name1} vs {name2}): p = {p:.4f}")
        if p < 0.05:
            print("   → Significant difference")

compare_models('ROUGE-L', t5_results,      bart_results,    'T5',   'BART')
compare_models('ROUGE-L', t5_results,      pegasus_results, 'T5',   'Pegasus')
compare_models('ROUGE-L', bart_results,    pegasus_results, 'BART', 'Pegasus')